#include "chipmunk/chipmunk.c"  
#undef STR
#undef XSTR
#undef SWAP
#include "chipmunk/cpArbiter.c"  
#include "chipmunk/cpArray.c"  
#include "chipmunk/cpBBTree.c"  
#undef DEF_UNIT_NAME
#undef A
#undef B
#undef STAMP
#undef PAIRS
#undef CP_BBTREE_DEBUG_DRAW
#include "chipmunk/cpBody.c"  
#include "chipmunk/cpCollision.c"  
#undef DRAW_ALL
#undef DRAW_GJK
#undef DRAW_EPA
#undef DRAW_CLOSEST
#undef DRAW_CLIP
#undef PRINT_LOG
#undef MAX_GJK_ITERATIONS
#undef MAX_EPA_ITERATIONS
#undef WARN_GJK_ITERATIONS
#undef WARN_EPA_ITERATIONS
#include "chipmunk/cpConstraint.c"  
#include "chipmunk/cpDampedRotarySpring.c"  
#include "chipmunk/cpDampedSpring.c"  
#include "chipmunk/cpGearJoint.c"  
#include "chipmunk/cpGrooveJoint.c"  
#include "chipmunk/cpHashSet.c"  
/*
#include "chipmunk/cpHastySpace.c"  
#undef WIN32_LEAN_AND_MEAN
#undef NOMINMAX
#undef ETIMEDOUT
#undef vld
#undef vdup_n
#undef vst
#undef vst_lane
#undef vadd
#undef vsub
#undef vpadd
#undef vmul
#undef vmul_n
#undef vneg
#undef vget_lane
#undef vset_lane
#undef vmin
#undef vmax
#undef vrev
#undef MAX_THREADS
*/
#include "chipmunk/cpMarch.c"  
#include "chipmunk/cpPinJoint.c"  
#include "chipmunk/cpPivotJoint.c"  
#include "chipmunk/cpPolyline.c"  
#undef DEFAULT_POLYLINE_CAPACITY
#include "chipmunk/cpPolyShape.c"  
#include "chipmunk/cpRatchetJoint.c"  
#include "chipmunk/cpRobust.c"  
#include "chipmunk/cpRotaryLimitJoint.c"  
#include "chipmunk/cpShape.c"  
#undef CP_DefineShapeGetter
#include "chipmunk/cpSimpleMotor.c"  
#include "chipmunk/cpSlideJoint.c"  
#include "chipmunk/cpSpace.c"  
#include "chipmunk/cpSpaceComponent.c"  
#include "chipmunk/cpSpaceDebug.c"  
#include "chipmunk/cpSpaceHash.c"  
#include "chipmunk/cpSpaceQuery.c"  
#include "chipmunk/cpSpaceStep.c"  
#undef CP_CONTACTS_BUFFER_SIZE
#include "chipmunk/cpSpatialIndex.c"  
#include "chipmunk/cpSweep1D.c"  