// ./chipmunk/chipmunk.h
#undef CHIPMUNK_H
#undef CP_EXPORT
/*
#undef cpAssertSoft
#undef cpAssertWarn
#undef cpAssertHard
*/
//#undef CP_BUFFER_BYTES
//#undef cpcalloc
//#undef cprealloc
//#undef cpfree
//#undef CP_VERSION_MAJOR
//#undef CP_VERSION_MINOR
//#undef CP_VERSION_RELEASE
#undef CP_CONVEX_HULL
// ./chipmunk/chipmunk_ffi.h
#undef MAKE_REF
// ./chipmunk/chipmunk_private.h
#undef CHIPMUNK_PRIVATE_H
//#undef CP_HASH_COEF
//#undef CP_HASH_PAIR
#undef MAGIC_EPSILON
#undef cpAssertSpaceUnlocked
/*
#undef CP_BODY_FOREACH_CONSTRAINT
#undef CP_BODY_FOREACH_ARBITER
#undef CP_BODY_FOREACH_SHAPE
*/
#undef CP_BODY_FOREACH_COMPONENT
// ./chipmunk/chipmunk_structs.h
#undef CHIPMUNK_STRUCTS_H
#undef CP_POLY_SHAPE_INLINE_ALLOC
// ./chipmunk/chipmunk_types.h
/*
#undef CHIPMUNK_TYPES_H
#undef CP_USE_CGTYPES
#undef CP_USE_DOUBLES
#undef cpfsqrt
#undef cpfsin
#undef cpfcos
#undef cpfacos
#undef cpfatan2
#undef cpfmod
#undef cpfexp
#undef cpfpow
#undef cpffloor
#undef cpfceil
#undef CPFLOAT_MIN
#undef INFINITY
#undef CP_PI
#undef cpTrue
#undef cpFalse
#undef CP_NO_GROUP
#undef CP_ALL_CATEGORIES
#undef CP_WILDCARD_COLLISION_TYPE
*/
// ./chipmunk/chipmunk_unsafe.h
#undef CHIPMUNK_UNSAFE_H
// ./chipmunk/cpArbiter.h
//#undef CP_MAX_CONTACTS_PER_ARBITER
//#undef CP_ARBITER_GET_SHAPES
//#undef CP_ARBITER_GET_BODIES
// ./chipmunk/cpBB.h
#undef CHIPMUNK_BB_H
// ./chipmunk/cpBody.h
// ./chipmunk/cpConstraint.h
// ./chipmunk/cpDampedRotarySpring.h
// ./chipmunk/cpDampedSpring.h
// ./chipmunk/cpGearJoint.h
// ./chipmunk/cpGrooveJoint.h
// ./chipmunk/cpHastySpace.h
// ./chipmunk/cpMarch.h
// ./chipmunk/cpPinJoint.h
// ./chipmunk/cpPivotJoint.h
// ./chipmunk/cpPolyline.h
#undef cpPolylineConvexDecomposition_BETA
// ./chipmunk/cpPolyShape.h
// ./chipmunk/cpRatchetJoint.h
// ./chipmunk/cpRobust.h
// ./chipmunk/cpRotaryLimitJoint.h
// ./chipmunk/cpShape.h
// ./chipmunk/cpSimpleMotor.h
// ./chipmunk/cpSlideJoint.h
// ./chipmunk/cpSpace.h
// ./chipmunk/cpSpatialIndex.h
// ./chipmunk/cpTransform.h
#undef CHIPMUNK_TRANSFORM_H
// ./chipmunk/cpVect.h
#undef CHIPMUNK_VECT_H
// ./chipmunk/prime.h